# -*- coding: utf-8 -*-
"""Lab13 strings methods.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BLNenKTGk8WEJKyT8jRXvY7FG7_VDwW

1. Count all letters, digits, and special symbols in a string
"""

def count_chars_digits_symbols(input_str):
    chars = digits = symbols = 0
    for char in input_str:
        if char.isalpha():
            chars += 1
        elif char.isdigit():
            digits += 1
        else:
            symbols += 1
    return chars, digits, symbols

# Input string
input_str = "P@#yn26at^&i5ve"
chars, digits, symbols = count_chars_digits_symbols(input_str)
print(f"Chars = {chars} Digits = {digits} Symbols = {symbols}")

"""2. Remove duplicate characters from a string

"""

def remove_duplicate_chars(input_str):
    words = input_str.split()
    result = []

    for word in words:
        unique_chars = ""
        for char in word:
            if char not in unique_chars:
                unique_chars += char
        result.append(unique_chars)

    return ' '.join(result)

# Input string
input_str = "String and String Function"
output_str = remove_duplicate_chars(input_str)
print(f"Output: {output_str}")

"""3. Count Uppercase, Lowercase, special characters, and numbers in a string

"""

def count_case_special_numbers(input_str):
    upper = lower = numbers = special = 0
    for char in input_str:
        if char.isupper():
            upper += 1
        elif char.islower():
            lower += 1
        elif char.isdigit():
            numbers += 1
        else:
            special += 1
    return upper, lower, numbers, special

# Input string
input_str = "Hell0 W0rld ! 123 * # welcome to pYtHoN"
upper, lower, numbers, special = count_case_special_numbers(input_str)
print(f"UpperCase: {upper} LowerCase: {lower} NumberCase: {numbers} SpecialCase: {special}")

"""4. Count vowels in a string

"""

def count_vowels(input_str):
    vowels = "aeiouAEIOU"
    count = 0
    for char in input_str:
        if char in vowels:
            count += 1
    return count

# Input string
input_str = "Welcome to Python Assignment"
vowel_count = count_vowels(input_str)
print(f"Total vowels are: {vowel_count}")