# -*- coding: utf-8 -*-
"""LAB-4- Day-4 (Control Statements)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-IERb_fI63tbbt2lnyg_kUFHVhVjsYX

Mayuri Khatpe

1.     Write a Python program that takes a number as input and prints "Even" if the number is even and "Odd" if it's odd.
"""

# Take a number as input from the user
number = int(input("Enter a number: "))

# Check if the number is even or odd
if number % 2 == 0:
    print("Even")
else:
    print("Odd")

"""2.      Create a Python program that checks whether a person is eligible to vote (18 years or older) based on their age.


"""

# Take the age as input from the user
age = int(input("Enter your age: "))

# Check if the person is eligible to vote
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

"""3.      Write a Python program that determines if a given year is a leap year or not.


"""

# Take the year as input from the user
year = int(input("Enter a year: "))

# Check if the year is a leap year
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

"""4.      Create a Python program that checks if a user-given number is positive, negative, or zero.


"""

# Take a number as input from the user
number = float(input("Enter a number: "))

# Check if the number is positive, negative, or zero
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

"""5.      Write a Python program that determines the largest of three numbers entered by the user.


"""

# Take three numbers as input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

# Determine the largest number
if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

# Output the largest number
print(f"The largest number is: {largest}")