# -*- coding: utf-8 -*-
"""LAB-13 String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTKi2UllwVmz2if-FFkqC5YXydhGNbKQ

1. Count the occurrences of each word in a given sentence
"""

from collections import Counter

string = "To change the overall look of your document. To change the look available in the gallery"
# Split the string into words, lowercasing them for consistency
words = string.lower().split()
# Count the occurrences of each word
word_count = Counter(words)

# Print the occurrences of each word
for word, count in word_count.items():
    print(f"{word}: {count}")

"""2. Remove a newline in Python

"""

string = "\nBest \nDeeptech \nPython \nTraining\n"
# Remove newlines by replacing them with an empty string
clean_string = string.replace("\n", "")
print(clean_string)

"""3. Reverse words in a string

"""

string = "Deeptech Python Training"
# Split the string into words, reverse them, and join them back into a string
reversed_words = ' '.join(string.split()[::-1])
print(reversed_words)

"""4. Count and display the vowels in a given text

"""

string = "Welcome to python Training"
vowels = "aeiouAEIOU"
# Use a list comprehension to find vowels in the string
vowel_list = [char for char in string if char in vowels]
# Count the number of vowels
vowel_count = len(vowel_list)

print(f"Vowels: {' '.join(vowel_list)}")
print(f"Total number of vowels: {vowel_count}")