# -*- coding: utf-8 -*-
"""LAB-11  While Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSCV_1Q4P8zemvM2rNf1XpXjL0IXs8Wv

Program to reverse a number using a while loop:
"""

# Program to reverse a number using a while loop
num = int(input("Enter a number: "))
reversed_num = 0

while num > 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num = num // 10

print("Reversed Number:", reversed_num)

"""Program to check whether a number is palindrome or not:

"""

# Program to check if a number is a palindrome
num = int(input("Enter a number: "))
original_num = num
reversed_num = 0

while num > 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num = num // 10

if original_num == reversed_num:
    print(original_num, "is a palindrome.")
else:
    print(original_num, "is not a palindrome.")

"""Program to find the factorial of a given number using a while loop:

"""

# Program to find the factorial of a given number using a while loop
num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    while num > 0:
        factorial *= num
        num -= 1

    print("Factorial:", factorial)

"""Program to accept numbers until the user enters 0 and display the sum of all the numbers:

"""

# Program to accept numbers until the user enters 0 and display the sum of all the numbers
total_sum = 0

while True:
    num = int(input("Enter a number (enter 0 to stop): "))
    if num == 0:
        break
    total_sum += num

print("Sum of all numbers:", total_sum)