# -*- coding: utf-8 -*-
"""Lab-10 functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19C0563f8VGWZgGlvrwZ8NK1a7YNXloLv

MAYURI KHATPE

Program to declare a div() function with two parameters to display their division:
"""

def div(a, b):
    result = a / b
    print(f"The division of {a} and {b} is: {result}")

# Calling the function
div(10, 2)

"""Program to declare a square() function with one parameter and display the square of that number:"""

def square(x):
    result = x * x
    print(f"The square of {x} is: {result}")

# Calling the function
square(5)

"""Program using max() and min() to display the maximum and minimum of 5 random numbers:"""

import random

numbers = [random.randint(1, 100) for _ in range(5)]
print("Random numbers:", numbers)
print("Maximum number is:", max(numbers))
print("Minimum number is:", min(numbers))

"""Program to accept a name from the user and display it in lower case:

"""

name = input("Enter your name: ")
print("Your name in lower case is:", name.lower())