# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkQiSsytd5q9cywuinhcqugWjVOESVab

1. Python program to sum all the items in a list:
"""

def sum_list(items):
    return sum(items)

# Example usage:
my_list = [1, 2, 3, 4, 5]
total = sum_list(my_list)
print(f"Sum of all items in the list: {total}")

"""2. Python program to traverse a given list in reverse order, and print the elements with the original index:"""

def traverse_reverse_with_index(lst):
    for i in range(len(lst)-1, -1, -1):
        print(f"Index {i}: {lst[i]}")

# Example usage:
original_list = ['red', 'green', 'white', 'black']
print("Traverse the list in reverse order with original index:")
traverse_reverse_with_index(original_list)