# -*- coding: utf-8 -*-
"""LAB-3 -Day-3(Programming Statements)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzrKQlWvC0o2WU-UkwT2GJ5hIjHdLEef

1. Using input() function take one number from the user and using ternary operators check whether the number is even or odd
"""

# Take a number input from the user
number = int(input("Enter a number: "))

# Check if the number is even or odd using a ternary operator
result = "Even" if number % 2 == 0 else "Odd"

# Output the result
print(f"The number {number} is {result}.")

"""2. Using input function take two number and then swap the number


"""

# Take two numbers as input from the user
a = input("Enter the first number (a): ")
b = input("Enter the second number (b): ")

# Swap the numbers
a, b = b, a

# Output the swapped values
print(f"After swapping:\nFirst number (a): {a}\nSecond number (b): {b}")

"""3. Write a Program to Convert Kilometers to Miles


"""

# Program to convert kilometers to miles

# Take input in kilometers from the user
kilometers = float(input("Enter the distance in kilometers: "))

# Conversion factor from kilometers to miles
conversion_factor = 0.621371

# Convert kilometers to miles
miles = kilometers * conversion_factor

# Output the result
print(f"{kilometers} kilometers is equal to {miles} miles.")

"""4. Find the Simple Interest on Rs. 200 for 5 years at 5% per year.


"""

# Principal amount
P = 200

# Rate of interest per year
R = 5

# Time period in years
T = 5

# Calculate Simple Interest
simple_interest = (P * R * T) / 100

# Output the result
print(f"The Simple Interest on Rs. {P} for {T} years at {R}% per year is Rs. {simple_interest}.")